# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceLike' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'SVProgressHUD'


  # Pods for FaceLike

  target 'FaceLikeTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.5'
    # Pods for testing
  end

end
